/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/album`; params?: Router.UnknownInputParams; } | { pathname: `/editAvatar`; params?: Router.UnknownInputParams; } | { pathname: `/editProfile`; params?: Router.UnknownInputParams; } | { pathname: `/homeapp`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/myPosts`; params?: Router.UnknownInputParams; } | { pathname: `/newPost`; params?: Router.UnknownInputParams; } | { pathname: `/pageA`; params?: Router.UnknownInputParams; } | { pathname: `/pageB`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/signUp`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/album`; params?: Router.UnknownOutputParams; } | { pathname: `/editAvatar`; params?: Router.UnknownOutputParams; } | { pathname: `/editProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/homeapp`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/myPosts`; params?: Router.UnknownOutputParams; } | { pathname: `/newPost`; params?: Router.UnknownOutputParams; } | { pathname: `/pageA`; params?: Router.UnknownOutputParams; } | { pathname: `/pageB`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/signUp`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/album${`?${string}` | `#${string}` | ''}` | `/editAvatar${`?${string}` | `#${string}` | ''}` | `/editProfile${`?${string}` | `#${string}` | ''}` | `/homeapp${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/myPosts${`?${string}` | `#${string}` | ''}` | `/newPost${`?${string}` | `#${string}` | ''}` | `/pageA${`?${string}` | `#${string}` | ''}` | `/pageB${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/signUp${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/album`; params?: Router.UnknownInputParams; } | { pathname: `/editAvatar`; params?: Router.UnknownInputParams; } | { pathname: `/editProfile`; params?: Router.UnknownInputParams; } | { pathname: `/homeapp`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/myPosts`; params?: Router.UnknownInputParams; } | { pathname: `/newPost`; params?: Router.UnknownInputParams; } | { pathname: `/pageA`; params?: Router.UnknownInputParams; } | { pathname: `/pageB`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/signUp`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
